//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 07:46:49 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kotar.com.br/web/soap/schema/fornecedor", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.kotar.web.soap.schema.fornecedor;
