//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 07:46:49 AM BRT 
//


package br.com.kotar.web.soap.schema.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bairro complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bairro"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="bairro_nome" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bairro_cidade" type="{http://kotar.com.br/web/soap/schema/common}cidade"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bairro", propOrder = {
    "bairroNome",
    "bairroCidade"
})
public class Bairro {

    @XmlElement(name = "bairro_nome", required = true)
    protected String bairroNome;
    @XmlElement(name = "bairro_cidade", required = true)
    protected Cidade bairroCidade;

    /**
     * Gets the value of the bairroNome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBairroNome() {
        return bairroNome;
    }

    /**
     * Sets the value of the bairroNome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBairroNome(String value) {
        this.bairroNome = value;
    }

    /**
     * Gets the value of the bairroCidade property.
     * 
     * @return
     *     possible object is
     *     {@link Cidade }
     *     
     */
    public Cidade getBairroCidade() {
        return bairroCidade;
    }

    /**
     * Sets the value of the bairroCidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cidade }
     *     
     */
    public void setBairroCidade(Cidade value) {
        this.bairroCidade = value;
    }

}
