//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 07:46:49 AM BRT 
//


package br.com.kotar.web.soap.schema.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cidade complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cidade"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cidade_nome" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cidade_estado" type="{http://kotar.com.br/web/soap/schema/common}estado"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cidade", propOrder = {
    "cidadeNome",
    "cidadeEstado"
})
public class Cidade {

    @XmlElement(name = "cidade_nome", required = true)
    protected String cidadeNome;
    @XmlElement(name = "cidade_estado", required = true)
    protected Estado cidadeEstado;

    /**
     * Gets the value of the cidadeNome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCidadeNome() {
        return cidadeNome;
    }

    /**
     * Sets the value of the cidadeNome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCidadeNome(String value) {
        this.cidadeNome = value;
    }

    /**
     * Gets the value of the cidadeEstado property.
     * 
     * @return
     *     possible object is
     *     {@link Estado }
     *     
     */
    public Estado getCidadeEstado() {
        return cidadeEstado;
    }

    /**
     * Sets the value of the cidadeEstado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Estado }
     *     
     */
    public void setCidadeEstado(Estado value) {
        this.cidadeEstado = value;
    }

}
