//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 07:46:49 AM BRT 
//


package br.com.kotar.web.soap.schema.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cliente complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cliente"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cliente_id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="cliente_nome" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cpf" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cliente", propOrder = {
    "clienteId",
    "clienteNome",
    "cpf"
})
public class Cliente {

    @XmlElement(name = "cliente_id")
    protected long clienteId;
    @XmlElement(name = "cliente_nome", required = true)
    protected String clienteNome;
    @XmlElement(required = true)
    protected String cpf;

    /**
     * Gets the value of the clienteId property.
     * 
     */
    public long getClienteId() {
        return clienteId;
    }

    /**
     * Sets the value of the clienteId property.
     * 
     */
    public void setClienteId(long value) {
        this.clienteId = value;
    }

    /**
     * Gets the value of the clienteNome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClienteNome() {
        return clienteNome;
    }

    /**
     * Sets the value of the clienteNome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClienteNome(String value) {
        this.clienteNome = value;
    }

    /**
     * Gets the value of the cpf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpf() {
        return cpf;
    }

    /**
     * Sets the value of the cpf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpf(String value) {
        this.cpf = value;
    }

}
