//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 07:46:49 AM BRT 
//


package br.com.kotar.web.soap.schema.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cotacao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cotacao"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cotacao_id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="cotacao_nome" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cliente" type="{http://kotar.com.br/web/soap/schema/common}cliente"/&gt;
 *         &lt;element name="cotacao_endereco" type="{http://kotar.com.br/web/soap/schema/common}cotacaoEndereco"/&gt;
 *         &lt;element name="codigo_voucher" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="itens" type="{http://kotar.com.br/web/soap/schema/common}cotacaoItemFornecedor" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cotacao", propOrder = {
    "cotacaoId",
    "cotacaoNome",
    "cliente",
    "cotacaoEndereco",
    "codigoVoucher",
    "itens"
})
public class Cotacao {

    @XmlElement(name = "cotacao_id")
    protected long cotacaoId;
    @XmlElement(name = "cotacao_nome", required = true)
    protected String cotacaoNome;
    @XmlElement(required = true)
    protected Cliente cliente;
    @XmlElement(name = "cotacao_endereco", required = true)
    protected CotacaoEndereco cotacaoEndereco;
    @XmlElement(name = "codigo_voucher", required = true)
    protected String codigoVoucher;
    protected List<CotacaoItemFornecedor> itens;

    /**
     * Gets the value of the cotacaoId property.
     * 
     */
    public long getCotacaoId() {
        return cotacaoId;
    }

    /**
     * Sets the value of the cotacaoId property.
     * 
     */
    public void setCotacaoId(long value) {
        this.cotacaoId = value;
    }

    /**
     * Gets the value of the cotacaoNome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCotacaoNome() {
        return cotacaoNome;
    }

    /**
     * Sets the value of the cotacaoNome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCotacaoNome(String value) {
        this.cotacaoNome = value;
    }

    /**
     * Gets the value of the cliente property.
     * 
     * @return
     *     possible object is
     *     {@link Cliente }
     *     
     */
    public Cliente getCliente() {
        return cliente;
    }

    /**
     * Sets the value of the cliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cliente }
     *     
     */
    public void setCliente(Cliente value) {
        this.cliente = value;
    }

    /**
     * Gets the value of the cotacaoEndereco property.
     * 
     * @return
     *     possible object is
     *     {@link CotacaoEndereco }
     *     
     */
    public CotacaoEndereco getCotacaoEndereco() {
        return cotacaoEndereco;
    }

    /**
     * Sets the value of the cotacaoEndereco property.
     * 
     * @param value
     *     allowed object is
     *     {@link CotacaoEndereco }
     *     
     */
    public void setCotacaoEndereco(CotacaoEndereco value) {
        this.cotacaoEndereco = value;
    }

    /**
     * Gets the value of the codigoVoucher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoVoucher() {
        return codigoVoucher;
    }

    /**
     * Sets the value of the codigoVoucher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoVoucher(String value) {
        this.codigoVoucher = value;
    }

    /**
     * Gets the value of the itens property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itens property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItens().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CotacaoItemFornecedor }
     * 
     * 
     */
    public List<CotacaoItemFornecedor> getItens() {
        if (itens == null) {
            itens = new ArrayList<CotacaoItemFornecedor>();
        }
        return this.itens;
    }

}
