//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 07:46:49 AM BRT 
//


package br.com.kotar.web.soap.schema.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cotacaoItemFornecedor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cotacaoItemFornecedor"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cotacaoItem" type="{http://kotar.com.br/web/soap/schema/common}cotacaoItem"/&gt;
 *         &lt;element name="valor_unitario" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="marca_modelo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cotacaoItemFornecedor", propOrder = {
    "cotacaoItem",
    "valorUnitario",
    "marcaModelo"
})
public class CotacaoItemFornecedor {

    @XmlElement(required = true)
    protected CotacaoItem cotacaoItem;
    @XmlElement(name = "valor_unitario")
    protected double valorUnitario;
    @XmlElement(name = "marca_modelo", required = true)
    protected String marcaModelo;

    /**
     * Gets the value of the cotacaoItem property.
     * 
     * @return
     *     possible object is
     *     {@link CotacaoItem }
     *     
     */
    public CotacaoItem getCotacaoItem() {
        return cotacaoItem;
    }

    /**
     * Sets the value of the cotacaoItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CotacaoItem }
     *     
     */
    public void setCotacaoItem(CotacaoItem value) {
        this.cotacaoItem = value;
    }

    /**
     * Gets the value of the valorUnitario property.
     * 
     */
    public double getValorUnitario() {
        return valorUnitario;
    }

    /**
     * Sets the value of the valorUnitario property.
     * 
     */
    public void setValorUnitario(double value) {
        this.valorUnitario = value;
    }

    /**
     * Gets the value of the marcaModelo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarcaModelo() {
        return marcaModelo;
    }

    /**
     * Sets the value of the marcaModelo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarcaModelo(String value) {
        this.marcaModelo = value;
    }

}
