//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 07:46:49 AM BRT 
//


package br.com.kotar.web.soap.schema.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cotacaoEndereco complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cotacaoEndereco"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cep" type="{http://kotar.com.br/web/soap/schema/common}cep"/&gt;
 *         &lt;element name="complemento" type="{http://kotar.com.br/web/soap/schema/common}enderecoComplemento"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cotacaoEndereco", propOrder = {
    "cep",
    "complemento"
})
public class CotacaoEndereco {

    @XmlElement(required = true)
    protected Cep cep;
    @XmlElement(required = true)
    protected EnderecoComplemento complemento;

    /**
     * Gets the value of the cep property.
     * 
     * @return
     *     possible object is
     *     {@link Cep }
     *     
     */
    public Cep getCep() {
        return cep;
    }

    /**
     * Sets the value of the cep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cep }
     *     
     */
    public void setCep(Cep value) {
        this.cep = value;
    }

    /**
     * Gets the value of the complemento property.
     * 
     * @return
     *     possible object is
     *     {@link EnderecoComplemento }
     *     
     */
    public EnderecoComplemento getComplemento() {
        return complemento;
    }

    /**
     * Sets the value of the complemento property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnderecoComplemento }
     *     
     */
    public void setComplemento(EnderecoComplemento value) {
        this.complemento = value;
    }

}
