//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 07:46:49 AM BRT 
//


package br.com.kotar.web.soap.schema.produto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import br.com.kotar.web.soap.schema.common.ProdutoFoto;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="detalhamento" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="foto" type="{http://kotar.com.br/web/soap/schema/common}produtoFoto" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="precoUnitario" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="uuidFornecedor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="identificador" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nome",
    "detalhamento",
    "foto",
    "precoUnitario",
    "uuidFornecedor",
    "identificador",
    "token"
})
@XmlRootElement(name = "persistirProdutoRequest")
public class PersistirProdutoRequest {

    @XmlElement(required = true)
    protected String nome;
    @XmlElement(required = true)
    protected String detalhamento;
    protected List<ProdutoFoto> foto;
    protected double precoUnitario;
    @XmlElement(required = true)
    protected String uuidFornecedor;
    @XmlElement(required = true)
    protected String identificador;
    @XmlElement(required = true)
    protected String token;

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the detalhamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetalhamento() {
        return detalhamento;
    }

    /**
     * Sets the value of the detalhamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetalhamento(String value) {
        this.detalhamento = value;
    }

    /**
     * Gets the value of the foto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the foto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFoto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProdutoFoto }
     * 
     * 
     */
    public List<ProdutoFoto> getFoto() {
        if (foto == null) {
            foto = new ArrayList<ProdutoFoto>();
        }
        return this.foto;
    }

    /**
     * Gets the value of the precoUnitario property.
     * 
     */
    public double getPrecoUnitario() {
        return precoUnitario;
    }

    /**
     * Sets the value of the precoUnitario property.
     * 
     */
    public void setPrecoUnitario(double value) {
        this.precoUnitario = value;
    }

    /**
     * Gets the value of the uuidFornecedor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuidFornecedor() {
        return uuidFornecedor;
    }

    /**
     * Sets the value of the uuidFornecedor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuidFornecedor(String value) {
        this.uuidFornecedor = value;
    }

    /**
     * Gets the value of the identificador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificador() {
        return identificador;
    }

    /**
     * Sets the value of the identificador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificador(String value) {
        this.identificador = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

}
