//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 07:46:49 AM BRT 
//


package br.com.kotar.web.soap.schema.cotacao;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import br.com.kotar.web.soap.schema.common.Cotacao;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cotacao" type="{http://kotar.com.br/web/soap/schema/common}cotacao"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cotacao"
})
@XmlRootElement(name = "getInfoCotacaoResponse")
public class GetInfoCotacaoResponse {

    @XmlElement(required = true)
    protected Cotacao cotacao;

    /**
     * Gets the value of the cotacao property.
     * 
     * @return
     *     possible object is
     *     {@link Cotacao }
     *     
     */
    public Cotacao getCotacao() {
        return cotacao;
    }

    /**
     * Sets the value of the cotacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cotacao }
     *     
     */
    public void setCotacao(Cotacao value) {
        this.cotacao = value;
    }

}
